### PR TITLE
Vendor minimize

### PR DESCRIPTION
**Pull request by paledega**
so file replace smaler file.
kanged from another xiaomi
tested. works well

### CODE REVIEW

**Comment by RenaRyuuguu** [comment]
@paledega 🤣

**Comment by rcstar6696** [comment]
No way like that. First of no device name from where file is. And our vendor partion is big enough. Third why ? Should i change that file ?

**Comment by paledega** [comment]
https://gitlab.e.foundation/e/devices/xiaomi/proprietary_vendor_xiaomi/-/blob/lineage-16.0/jason/proprietary/vendor/lib64/libril-qc-hal-qmi.so
smaller than original one.

and ldd output doesnt have any issue

**Comment by rcstar6696** [comment]
This was not the answer to my question !! ???

**Comment by paledega** [comment]
all custom and stock roms are too big. 700mb+

**Comment by rcstar6696** [comment]
And why does that matter ? I will 100% sure never merge stuff like that. You simply copy stuff together randomly just to save arround 20mb ? It has a reason why we use stock files because its a rule in code of conduct for roms. Various file copy is not allowed. Mostly there is a reason why a File is smaller than a other one. Its not smaller just because its compiled on diffrent computer or server. You will lose compatibility or features you may not notice

**Comment by DarkAmy** [comment]
@rcstar6696 +69

**Comment by paledega** [comment]
some xiaomi devices so files are striped but some not striped.
I found striped so file from another xiaomi

**Comment by paledega** [comment]
if you want you can test

**Comment by rcstar6696** [comment]
Ok read what i wrote in longer text Ou may understand. A vendor minimize is not planed and no reason for that given which makes any sense to me

**Comment by rcstar6696** [comment]
I will never test stuff like that because its wrong

**Comment by paledega** [comment]
No problem.

**Pull request closed without merging**
